SELECT * FROM COUNTRY WHERE COUNTRY LIKE 'A%a';
SELECT * FROM COUNTRY WHERE COUNTRY LIKE '%_____n';
SELECT * FROM FILM WHERE TITLE ILIKE '%T%T%T%T%';
SELECT * FROM FILM WHERE LENGTH>90 AND RENTAL_RATE=2.99 AND TITLE LIKE 'C%';