SELECT TITLE,LENGTH FROM film
WHERE title LIKE '%n'
ORDER BY length DESC
LIMIT 5;

SELECT TITLE,LENGTH FROM film
WHERE title LIKE '%n'
ORDER BY length ASC
OFFSET 5
LIMIT 5;

SELECT LAST_NAME,STORE_ID FROM CUSTOMER
WHERE STORE_ID = 1
ORDER BY LAST_NAME DESC
LIMIT 4;


