SELECT COUNT (*) AS COUNT
FROM FILM
WHERE LENGTH >
		(SELECT AVG(LENGTH)
			FROM FILM);


SELECT COUNT (*) AS COUNT
FROM FILM
WHERE RENTAL_RATE =
		(SELECT MAX(RENTAL_RATE)
			FROM FILM);


SELECT TITLE,
	RENTAL_RATE,
	REPLACEMENT_COST
FROM FILM
WHERE (RENTAL_RATE =
								(SELECT MIN(RENTAL_RATE)
									FROM FILM)
							AND REPLACEMENT_COST =
								(SELECT MIN(REPLACEMENT_COST)
									FROM FILM));


SELECT CUSTOMER_ID,
	MAX(CUSTOMER_ID_COUNT)
FROM
	(SELECT CUSTOMER_ID,
			COUNT(CUSTOMER_ID) AS CUSTOMER_ID_COUNT
		FROM PAYMENT
		GROUP BY CUSTOMER_ID
		ORDER BY CUSTOMER_ID_COUNT DESC) AS D
GROUP BY D.CUSTOMER_ID
ORDER BY MAX DESC
LIMIT 5;






													
